# Base stage for runtime (used in both debug and production)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

# Install required system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libgssapi-krb5-2 \
    libicu-dev \
    && rm -rf /var/lib/apt/lists/*  # we install for because it Cannot load library libgssapi_krb5.so.2 

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["./Message_app/Message_app.csproj", "Message_app/"]
RUN dotnet restore "./Message_app/Message_app.csproj"
COPY . .
WORKDIR "/src/Message_app"
RUN dotnet build "./Message_app.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Publish stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Message_app.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Final production image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Message_app.dll"]